services:
  - type: web
    name: gard-ai-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: IMGBB_API_KEY
        sync: false
